version: '3'
services:
  server:
    image: server
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  client:
    image: client
    build:
      context: ./client
    ports:
      - "5173:5173"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
